safe: true
lsi: false
highlighter: pygments
paginate: 5
paginate_path: "blog/p/:num/"
baseurl: "http://rogersuen.github.io"
permalink: /:year/:month/:title.html

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      author: "Roger Suen"

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
